### ISSUE TITLE
arrow key doesn't work

### ISSUE THREAD

**Issue by j5shi** [lpenz/vimcommander#8]
I have `<up>` and `<down>` with the following mappings:

```vim
   <Up>         @<Plug>VimCommanderGotoPrevEntry
        Last set from ~/.vim/bundle/vimcommander/plugin/vimcommander.vim
n  <Up>        * k
        Last set from ~/.vimrc

   <Down>       @<Plug>VimCommanderGotoNextEntry
        Last set from ~/.vim/bundle/vimcommander/plugin/vimcommander.vim
n  <Down>      * j
        Last set from ~/.vimrc
```

The problem is in vimcommander panels, `<up>` and `<down>` will enter in command mode and key in:

```vim
:cal <SNR>83_GotoNextEntry()
```

without trigerring the call.

**Comment by j5shi** [comment]
So I tried to change the `<up>` and `<down>`'s mapping like this (end up with `<CR>`) and this worked:

```vim
    map <silent> <buffer> <Down>           <Plug>VimCommanderGotoNextEntry<CR>
    map <silent> <buffer> <Up>             <Plug>VimCommanderGotoPrevEntry<CR>
```

**Comment by lpenz** [comment]
That's odd. What kind of terminal are you using?
That only happens with the up/down keys or are other keys affected as well?

**Comment by j5shi** [comment]
I'm using `mintty.exe` which comes with cygwin by default. The term I'm using is `xterm-256color`. up/down are the only key mappings that need to be changed to work so far.

**Comment by lpenz** [comment]
I just tested it and it keeps working for me. I just realized that I usually use k/j to go up/down, so I wouldn't have noticed that anyway.

**Comment by j5shi** [comment]
Thanks :+1:
